### ISSUE TITLE
Create project in Stoplight

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mds-openapi#1]
Follow approach in [`cds-openapi`](https://github.com/openmobilityfoundation/cds-openapi) to connect Stoplight project to this GitHub repository via the @omf-service-account.

**Comment by schnuerle** [comment]
Project created in Stoplight:
https://openmobilityfnd.stoplight.io/settings/mds-openapi

And connected with @omf-service-account.

**Comment by thekaveman** [comment]
@schnuerle when you get a chance, can you please confirm that @omf-service-account has write permissions on this repo?

**Comment by schnuerle** [comment]
FYI I have confirmed this and sent you a message and screenshot on Slack.
