### ISSUE TITLE
Media type in OpenAPI

### ISSUE THREAD

**Issue by thekaveman** [openmobilityfoundation/mds-openapi#34]
## UPDATE

See comment below https://github.com/openmobilityfoundation/mds-openapi/issues/34#issuecomment-1534066482

## Original

MDS defines the media type `application/vnd.mds+json` for use in the (response) `Content-type` header, and for the purposes of version negotiation whereby a client could request a particular version:

```
Accept application/vnd.mds+json;version=2.0
```

The OpenAPI endpoints thus far have used `application/vnd.mds+json` as the `Content-type` and not required it as an Accept header.

**Comment by thekaveman** [comment]
It seems like there is no way to distinguish the two (Accept vs. Content-type) in OpenAPI 3.1 or earlier. 

Each [`Media Type Object`](https://spec.openapis.org/oas/latest.html#media-type-object) defines both the request and response media type.

@schnuerle -- which should we use in the MDS OpenAPI docs?

* `application/vnd.mds+json` is what the spec says it should be, but...
* `application/json` renders much nicer in the Stoplight website, giving an immediate preview vs. having to click to "Send request" with the above type

## As `application/vnd.mds+json`

Here we see a "Send request" link

<img width="950" alt="image" src="https://user-images.githubusercontent.com/1783439/236110073-1c5dd737-4cfa-4b8b-8a16-a7cc8d2cffcf.png">

Clicking that (sometimes) gives a preview

<img width="935" alt="image" src="https://user-images.githubusercontent.com/1783439/236110104-10b5c1b3-8011-4b6b-93a2-79640cd2529e.png">

## As `application/json`

Here we immediately see a preview without clicking any buttons ("Send request" is still available)

<img width="964" alt="image" src="https://user-images.githubusercontent.com/1783439/236110149-463921a7-71fa-491f-a5ab-ad7ce288026e.png">

**Comment by schnuerle** [comment]
Ah I prefer the application/json render and I think it makes sense for this work to use that.

**Comment by thekaveman** [comment]
Great, that's what I went with!
